import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

import CustomNavBar from "@/components/customNavBar";
import Footer from "@/components/Footer";
import UserProvider from "@/context/userProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserProvider>
        <ToastContainer />
        <div className="text-black">
          <CustomNavBar />
          <div className="m-2">

            {children}
          </div>
          <Footer />
        </div>
        </UserProvider>
      </body>
    </html>
  );
}
